apps/sales/urls.py
# ZeroPaul
from django.urls import path, include
from apps.sales.views.sale import SaleListView, SaleCreateUpdateView, ProductAutocompleteView
from apps.sales.views.pdf import SalePDFView


app_name = 'sales'

urlpatterns = [
    path('sale/', SaleListView.as_view(), name='sale_list'),
    path('sale/create/', SaleCreateUpdateView.as_view(), name='sale_create'),
    path('sale/<int:pk>/edit/', SaleCreateUpdateView.as_view(), name='sale_edit'),
    path('sale-product/', ProductAutocompleteView.as_view(), name='sale_auto_product'),
    path(
        route ='sale-pdf/<int:pk>/',
        view = SalePDFView.as_view(),
        name = 'sale_pdf'
    ),
]

armfy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.auths.urls")),
    path('', include("apps.dashboards.urls")),
    path('', include("apps.products.urls")),
    path('', include('apps.sales.urls', namespace='sales')),
]

apps/sales/models/sale.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.products.models.product import Product
from apps.sales.models.voucher import NumerationVoucher


class Sale(models.Model):
    # fields
    customer = models.CharField(max_length=255)
    numeration_voucher = models.ForeignKey(
        NumerationVoucher, on_delete=models.CASCADE,
        related_name='sales_numeration_voucher'
    )
    date_sale = models.DateTimeField(auto_now_add=True)

    class Meta:
        # ordering = ['field',]
        verbose_name = _('Sale')
        verbose_name_plural = _('Sales')

    def __str__(self):
        return f'{ self.customer} - { self.date_sale.date()}'
    
    def save(self, *args, **kwargs):
        # self.numeration_voucher.gen_correlative()
        print(self.id)
        super(Sale, self).save(*args, **kwargs)
        
    @property
    def total(self):
        return sum(detail.subtotal for detail in self.sale_sale_detail.all())
    
    def get_serie_number(self):
        return self.numeration_voucher.serie_voucher, self.numeration_voucher.number


class SaleDetail(models.Model):
    # fields
    sale = models.ForeignKey(
        Sale, on_delete=models.CASCADE,
        related_name='sale_sale_detail'
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE,
        related_name='product_sale_detail'
    )
    quantity = models.IntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        # ordering = ['name',]
        verbose_name = _('Sale Detail')
        verbose_name_plural = _('Sale Details')

    def __str__(self):
        return f'{self.product.__str__()} - {self.quantity}'
    
    @property
    def subtotal(self):
        return self.quantity * self.unit_price

apps/sales/models/voucher.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _


class TypeVoucher(models.Model):
    # fields
    voucher_name = models.CharField(max_length=255, unique=True)
    voucher_status = models.BooleanField(default=True)

    class Meta:
        # ordering = ['voucher_name',]
        verbose_name = _('TypeVoucher')
        verbose_name_plural = _('TypeVoucher s')

    def __str__(self):
        return f'{self.voucher_name}'

class SerieVoucher(models.Model):
    # fields
    type_voucher = models.ForeignKey(
        TypeVoucher, on_delete=models.CASCADE,
        related_name='serie_vouchers_type_voucher'
    )
    serial_number = models.CharField(max_length=4, unique=True)
    serial_status = models.BooleanField(default=True)

    class Meta:
        # ordering = ['serial_number',]
        verbose_name = _('SerieVoucher')
        verbose_name_plural = _('SerieVouchers')

    def __str__(self):
        return f'{self.type_voucher.voucher_name}-{self.serial_number}'
    
class NumerationVoucher(models.Model):
    # fields
    serie_voucher = models.ForeignKey(
        SerieVoucher, on_delete=models.CASCADE,
        related_name='numeration_vouchers_serie_voucher'
    )
    number = models.IntegerField()

    class Meta:
        # ordering = ['name',]
        verbose_name = _('NumerationVoucher')
        verbose_name_plural = _('NumerationVouchers')

    def __str__(self):
        return f'{self.serie_voucher.__str__()}-{self.number}'
    
    def gen_correlative(self):
        last_number = NumerationVoucher.objects.all().filter(serie_voucher=self.serie_voucher).order_by('-number').first()
        print("---", last_number)
        gen_number = last_number + 1 if last_number else 1
        self.number = gen_number
        # self.save()

apps/sales/forms/sale.py
from apps.templifys.models import ModelForm
from apps.templifys import widgets
from apps.sales.models.sale import Sale

from django.db import models
class DynamicWidget():
    fields_widgets = {
        models.CharField: widgets.TextInput,
        models.IntegerField: widgets.NumberInput,
        models.EmailField: widgets.EmailInput,
        models.DateField: widgets.DateInput(attrs={'type': 'date'}),
        models.BooleanField: widgets.CheckboxInput,
        models.TextField: widgets.Textarea,
        models.FloatField: widgets.NumberInput,
        models.DecimalField: widgets.NumberInput,
        models.FileField: widgets.ClearableFileInput,
        models.ImageField: widgets.ClearableFileInput,
        models.URLField: widgets.URLInput,
        models.PositiveIntegerField: widgets.NumberInput,
        models.PositiveSmallIntegerField: widgets.NumberInput,
        models.SlugField: widgets.TextInput,
        models.TimeField: widgets.TimeInput(attrs={'type': 'time'}),
        models.GenericIPAddressField: widgets.TextInput,
        models.ForeignKey: widgets.Select(),
        models.ManyToManyField: widgets.CheckboxSelectMultiple,
        models.OneToOneField: widgets.Select(),
    }

    def __init__(self, model, fields):
        self.model = model
        self.fields = fields

    def generate_widgets(self):
        widgets = {}
        for field in self.model._meta.get_fields():
            if field.name in self.fields:
                widget = self.fields_widgets.get(type(field))
                widgets[field.name] = widget
                # print(f'Nombre: {field.name}, Tipo: {widget}')
        return widgets
    
class SaleForm(ModelForm):
    class Meta:
        model = Sale
        fields = ['customer', ]
        widgets = DynamicWidget(model=model, fields=fields).generate_widgets()

apps/sales/views/pdf.py
import os
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.template.loader import get_template
from django.views import View
from django.conf import settings
from io import BytesIO
from xhtml2pdf import pisa

class GeneratePDFView(View):
    model = None
    template_name = None
    obj_name = 'obj'

    def get(self, request, pk):
        obj = get_object_or_404(self.model, pk=pk)
        template = get_template(self.template_name)
        context = {
            self.obj_name: obj,
        }
        html = template.render(context)
        result = BytesIO()
        ticket_width = 80  # 80mm
        ticket_height = 200  # 200mm
        pdf = pisa.CreatePDF(
            html,
            dest=result,
            encoding='utf-8',
            link_callback=lambda uri, rel: self._fetch_resources(uri, rel),
            pageSize=(ticket_width * 2.83465, ticket_height * 2.83465)
        )
        if pdf.err:
            return HttpResponse('Error generating PDF')
        pdf_content = result.getvalue()
        response = HttpResponse(content_type='application/pdf')
        name_pdf = f'{obj.__str__()}.pdf'
        response['Content-Disposition'] = f'inline; filename={name_pdf}'
        response.write(pdf_content)
        return response

    def _fetch_resources(self, uri, rel):
        if uri.startswith(settings.STATIC_URL):
            path = os.path.join(settings.STATIC_ROOT, uri.replace(settings.STATIC_URL, ''))
            if os.path.exists(path):
                return path
        elif uri.startswith(settings.MEDIA_URL):
            path = os.path.join(settings.MEDIA_ROOT, uri.replace(settings.MEDIA_URL, ''))
            if os.path.exists(path):
                return path

        return None
    
    def reduce_word(self, prayer):
        sum_text = 0
        letters = ""
        for word in prayer.split():
            sum_text += len(word)
            if sum_text < 40:
                letters += word + " "
            elif sum_text > 40:
                letters += word[0] + "."
        return letters
    

from apps.sales.models.sale import Sale
class SalePDFView(GeneratePDFView):
    model = Sale
    template_name = 'sales/sale_pdf.html'
    obj_name = 'obj_sale'

apps/sales/views/sale.py
import json
from django.http import JsonResponse
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import View

from apps.templifys.builders.table import WidgetTable
from apps.templifys.views.viewmx import CreateUpdateViewMx
from apps.sales.models.sale import Sale, SaleDetail
from apps.sales.models.voucher import SerieVoucher, NumerationVoucher
from apps.sales.forms.sale import SaleForm

from django.db.models import Q
from operator import __or__ as OR
from functools import reduce


class SaleListView(LoginRequiredMixin, ListView):
    model = Sale
    template_name = 'sales/sale_list.html'
    context_object_name = 'sale_list'
    # paginate_by = 2

    def get_queryset(self):
        query = self.request.GET.get('search', '')
        queryall = (Q(customer__icontains=query),
                    Q(customer__icontains=query))
        queryset = Sale.objects.filter(reduce(OR, queryall))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['obj_table'] = WidgetTable(context)
        return context



class SaleCreateUpdateView(LoginRequiredMixin, View, CreateUpdateViewMx):
    model = Sale
    form_class = SaleForm
    template_name = 'sales/sale_form.html'
    success_url = 'sales:sale_list'

    def gen_numeration(self, id):
        get_serie_voucher = SerieVoucher.objects.filter(pk=id).first()
        last_number = NumerationVoucher.objects.filter(serie_voucher=get_serie_voucher).order_by('-number').first()
        gen_number = last_number.number + 1 if last_number else 1
        return gen_number, get_serie_voucher

    def create_numeration(self):
        id =  self.request.GET.get('type_voucher') if self.request.GET.get('type_voucher') is not None else 1
        n, serie = self.gen_numeration(id)
        obj_numeration = NumerationVoucher.objects.create(serie_voucher=serie, number=n)
        return obj_numeration
    
    # def get(self, request, pk=None, *args, **kwargs):
    #     response = super().get(request, pk, *args, **kwargs)
        
    #     return response
    
    def get_serie_voucher(self):
        return SerieVoucher.objects.filter(serial_status=True)

    def form_valid(self, form):
        from decimal import Decimal
        new_detail = False
        detail_sales = eval(self.request.POST.get('datos'))
        obj_form = form.save(commit=False)
        if obj_form.pk is None:
            new_detail = True
            new_nv = self.create_numeration()
            obj_form.numeration_voucher = new_nv
        obj_form.save()
        if new_detail:
            for detail in detail_sales:
                SaleDetail.objects.create(sale_id=obj_form.id, product_id=detail['id'], quantity=int(detail['quantity']), unit_price=Decimal(detail['unit_price']))
            new_detail = False
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if kwargs.get('pk'):
            s, n = kwargs.get('obj').get_serie_number()
        else:
            id =  self.request.GET.get('type_voucher') if self.request.GET.get('type_voucher') is not None else 1
            n, s = self.gen_numeration(id)
        context['numeration'] = n
        context['serial'] = s.serial_number
        context['type_vouchers'] = self.get_serie_voucher()
        return context


from apps.products.models.product import Product
class ProductAutocompleteView(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get('query', '')
        queryall = (Q(profile_steels_product__name_origin__icontains=query),
                    # Q(customer__icontains=query)
        )
        queryset = Product.objects.filter(reduce(OR, queryall))
        data_query = []
        for obj in queryset:
            data_query.append({
                'id': obj.id,
                'name': obj.__str__(),
            })
        return JsonResponse(data_query, safe= False)

apps/sales/templates/sales/sale_form.html
{% extends 'base.html' %}

{% block title %}
Armfy
{% endblock %}

{% block style %}
<style>
  input:focus-visible {
    outline: none;
}
  .mx-input-table {
    width: 50px;
    padding: 0px 0 !important;
  }
  .floating-list {
    position: absolute;
    z-index: 999;
    top: 100%;
    left: 0;
    width: 100%;
    background-color: black;
    color: aliceblue;
    border: 1px solid #ccc;
    list-style: none;
    padding: 0;
    margin: 0;
    display: none;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  }

</style>
{% endblock %}
{% block barname %}
{% if is_editing %}Editar{% else %}Crear{% endif %} Venta
{% endblock %}
{% block content %}

<div class="mx-card mdl-shadow--4dp mdl-cell mdl-cell--12-col mdl-grid">
  <a href="{% url 'sales:sale_list' %}">Volver a la lista</a>
  {% if is_editing %}{%else%}
  <form method="get" id="type_voucher-form">

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label getmdl-select getmdl-select__fix-height">
      <input type="text" value="" class="mdl-textfield__input" id="type_voucher" readonly>
      <input type="hidden" value="" name="type_voucher" id="hidden_type_voucher">
      <i class="mdl-icon-toggle__label material-icons">keyboard_arrow_down</i>
      <label for="type_voucher" class="mdl-textfield__label">Type Voucher</label>
      <ul for="type_voucher" class="mdl-menu mdl-menu--bottom-left mdl-js-menu" onclick="typeProSubmit(this)">
        {% for tv in type_vouchers %}
          <li class="mdl-menu__item" data-val="{{ tv.id }}">{{ tv.type_voucher }}</li>
        {% endfor %}
      </ul>
    </div>
  </form>
  {% endif %}
<div style="display: flex;">
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <input class="mdl-textfield__input" type="text" id="id_serie" name="serie" disabled value="{{ serial }}">
    <label class="mdl-textfield__label" for="id_serie">Serie</label>
  </div>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <input class="mdl-textfield__input" type="text" id="id_number" name="number" disabled value="{{ numeration }}">
    <label class="mdl-textfield__label" for="id_number">Number</label>
  </div>
</div>
  <form method="post" id="obj_form">
    {% csrf_token %}
    {{ obj_form.as_p }}
    <input type="hidden" id="datos" name="datos" value="">
    <button type="submit" onclick="agregarDatosExtra()">{% if is_editing %}Actualizar{% else %}Gen Sale{% endif %}</button>
  </form>

</div>
<div class="mx-card mdl-shadow--4dp mdl-cell mdl-cell--12-col mdl-grid">
<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
  <input class="mdl-textfield__input" type="text" id="description" name="add" autocomplete="off">
  <label class="mdl-textfield__label" for="description">Add Product</label>
</div>
<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" id="etable">
  <thead>
    <tr>
      <th>N°</th>
      <th>Description</th>
      <th>Cant</th>
      <th>P.Unit</th>
      <th>Sub Total</th>
      <th>Option</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="4">Total</td>
      <td>--</td>
      <td>
        
      </td>
    </tr>
  </tfoot>
</table>
</div>
{% endblock %}

{% block script %}
<script>
  function getDetail() {
    var datos = [];
    var filas = document.getElementById('etable').getElementsByTagName('tbody')[0].rows;
    console.log(filas);
    for (var i = 0; i < filas.length; i++){
      var id_pro = filas[i].cells[0].getAttribute('data-id');
      var quantity = filas[i].cells[2].querySelector('input').value;
      var unit_price = filas[i].cells[3].querySelector('input').value;
      datos.push({'id': id_pro, 'quantity': quantity, 'unit_price': unit_price});
    }
    return JSON.stringify(datos)


  }
  function agregarDatosExtra() {
    // Modifica el valor del campo oculto antes de enviar el formulario
    document.getElementById('datos').value = getDetail();
}
  function calTotal(){
    var suma = 0;
    var filas = document.getElementById('etable').getElementsByTagName('tbody')[0].rows;
    for (var i = 0; i < filas.length; i++){
      var subtotal = filas[i].cells[4];
      suma += parseFloat(subtotal.textContent) || 0;

    }
    var total = document.getElementById('etable').getElementsByTagName('tfoot')[0].rows;
    total[0].cells[1].textContent = suma.toFixed(2);
    getDetail();
  }

  function calSale(){
    var filas = document.getElementById('etable').getElementsByTagName('tbody')[0].rows;
    for (var i = 0; i < filas.length; i++){
      var inputs = filas[i].getElementsByTagName('input');
      console.log(inputs);
      var suma = 1;
      for (var j = 0; j < inputs.length; j++){
        suma *= parseFloat(inputs[j].value);
      }
      var subtotal = filas[i].cells[4];
      subtotal.textContent = suma.toFixed(2);
    }
    calTotal();
    
  }
  function generateUUID() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
      const r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
    });
  }
  
  const uuid = generateUUID();
  console.log(uuid);
  
    function createInput(description){
      const container = document.createElement('div');
      container.classList.add(
        'mdl-textfield', 'mdl-js-textfield', 
        'mdl-textfield--floating-label', 
        'is-upgraded', 'mx-input-table'
      );
      
      const id_uuid = generateUUID();
      container.setAttribute('data-upgraded',',MaterialTextfield');
      const input = document.createElement('input');
      input.classList.add('mdl-textfield__input');
      input.setAttribute('type', 'number');
      input.setAttribute('autocomplete', 'off');
      input.setAttribute('id', 'id_text_pro'+id_uuid);
      input.setAttribute('name', 'name_pro');
      input.value = description;
      input.addEventListener('input', function() {
        calSale();
      });
      container.appendChild(input);
      /*const label = document.createElement('label');
      label.classList.add('mdl-textfield__label');
      label.setAttribute('for', 'id_text_pro'+id_uuid);
      label.textContent = 'Product';
      container.appendChild(label);*/
      return container
    }
  let contador = 1;

        // Función para agregar una nueva fila
        function addProduct(np, ip) {
            const descripcion = np
            
            // Verificar si la descripción no está vacía
            if (descripcion !== '') {
                const tabla = document.getElementById('etable').getElementsByTagName('tbody')[0];

                // Crear una nueva fila
                const nuevaFila = tabla.insertRow();

                // Crear las celdas de la fila
                const celdaNro = nuevaFila.insertCell(0);
                celdaNro.setAttribute('data-id', ip);
                const celdaDescripcion = nuevaFila.insertCell(1);
                const celdaCant = nuevaFila.insertCell(2);
                const celdaPUnit = nuevaFila.insertCell(3);
                const celdaSTotal = nuevaFila.insertCell(4);
                const celdaAcciones = nuevaFila.insertCell(5);

                // Asignar el número y la descripción
                celdaNro.textContent = contador;
                // const inputDescripcion = createInput(descripcion)
                //celdaDescripcion.appendChild(inputDescripcion);
                celdaDescripcion.textContent = descripcion
                const inputCant = createInput(1)
                celdaCant.appendChild(inputCant)
                const inputPUnit = createInput(1)
                celdaPUnit.appendChild(inputPUnit)
                celdaSTotal.textContent = 1


                // Agregar un botón para eliminar la fila
                const botonEliminar = document.createElement('button');
                botonEliminar.textContent = 'Delete';
                botonEliminar.onclick = function() {
                    eliminarFila(nuevaFila);
                };
                celdaAcciones.appendChild(botonEliminar);

                // Incrementar el contador para la siguiente fila
                contador++;

                // Limpiar el campo de entrada
                document.getElementById('description').value = '';
                calTotal();
            } else {
                alert('Por favor, ingrese una descripción.');
            }
        }

        // Función para eliminar una fila
        function eliminarFila(fila) {
            const tabla = document.getElementById('etable').getElementsByTagName('tbody')[0];
            tabla.deleteRow(fila.rowIndex - 1); // Eliminar la fila del cuerpo de la tabla
            actualizarNumeracion(); // Actualizar los números de las filas
            calTotal();
        }

        // Función para actualizar la numeración de las filas
        function actualizarNumeracion() {
            const filas = document.getElementById('etable').getElementsByTagName('tbody')[0].rows;
            for (let i = 0; i < filas.length; i++) {
                filas[i].cells[0].textContent = i + 1; // Actualizar el número de la fila
            }
            contador = filas.length + 1; // Actualizar el contador global
        }

  // Selection

  function loadSelect(){
    const url = new URL(window.location.href);
    let param = url.searchParams.get('type_voucher');
    if (param === null){
      param = '1'
    }
    const form = document.getElementById('type_voucher-form');
    const obj =form.querySelector('ul');
    const elementosFiltrados = Array.from(obj.children).filter(li => li.getAttribute('data-val') === param);
    elementosFiltrados[0].setAttribute('data-selected', 'true');
  }
  loadSelect()

  
  function typeProSubmit(obj){
    const inputHidden = document.getElementById('hidden_type_voucher');
    const form = document.getElementById('type_voucher-form');
    const url = new URL(window.location.href);
    const param = url.searchParams.get('type_voucher');
    form.submit()
  }


  // AUTOCOMPLETE

  document.addEventListener('DOMContentLoaded', function() {
    const input = document.getElementById('description');

    input.addEventListener('input', function() {
      const query = input.value;

      // Solo realizar la búsqueda si el término tiene al menos 2 caracteres
      if (query.length >= 4) {
        fetch(`/sale-product/?query=${encodeURIComponent(query)}`)
          .then(response => response.json())
          .then(data => {
            // Mostrar los resultados de la búsqueda
            // Limpiar cualquier sugerencia previa
            closeSuggestions();

            if (data.length > 0) {
              const suggestionList = document.createElement('ul');
              suggestionList.classList.add('floating-list');
              //suggestionList.classList.add('mdl-menu', 'mdl-menu--bottom-left', 'mdl-js-menu');
              suggestionList.style.display = 'block';
              suggestionList.setAttribute('data-upgraded', ',MaterialMenu,MaterialRipple')
              data.forEach(item => {
                const suggestionItem = document.createElement('li');
                suggestionItem.textContent = item.name;
                suggestionItem.addEventListener('click', function() {
                  input.value = item.name;
                  addProduct(item.name, item.id)
                  closeSuggestions();
                });
                suggestionList.appendChild(suggestionItem);
              });

              input.parentElement.appendChild(suggestionList);
            }
          })
          .catch(error => console.error('Error fetching autocomplete data:', error));
      } else {
        closeSuggestions();
      }
    });

    // Función para cerrar las sugerencias
    function closeSuggestions() {
      const suggestionList = input.parentElement.querySelector('ul');
      if (suggestionList) {
        setTimeout(() => {
          suggestionList.style.display = 'none';
        }, 200);
        suggestionList.remove();
      }
    }
  });
  

</script>
{% endblock %}

apps/sales/templates/sales/sale_list copy.html
{% extends 'base.html' %}

{% block title %}
  Armfy - Sales
{% endblock %}

{% block style %}
  <style>
  </style>
{% endblock %}

{% block barname %}
  Sales
{% endblock %}
{% block content %}
<form id="search-form" method="GET">
  <input type="text" id="search-input" name="search" placeholder="Buscar evento" autocomplete="off" />
</form>

<ul id="event-list" style="background-color: white;">
  {% for evento in sale_list %}
      <li>{{ evento.customer }}</li>
  {% empty %}
      <li>No sales found</li>
  {% endfor %}
</ul>
{{ obj_table }}
{% endblock %}

{% block script %}
  <script>
    document.getElementById('search-input').addEventListener('input', function() {
      const query = this.value;  // Obtenemos el valor del campo de búsqueda

      // Realizamos la solicitud usando la API fetch
      fetch(`{% url 'sales:sale_list' %}?search=${query}`, {
          method: 'GET',
          headers: {
              'Content-Type': 'application/json',
              'X-Requested-With': 'XMLHttpRequest',
          }
      })
      .then(response => response.json())  // Esperamos la respuesta en formato JSON
      .then(data => {
          let eventList = document.getElementById('event-list');

          console.log(data)
          eventList.innerHTML = '';  // Limpiamos la lista actual

          if (data.sale_list.length > 0) {
              // Si hay resultados, los mostramos
              console.log('go')
              data.sale_list.forEach(evento => {
                  const li = document.createElement('li');
                  li.textContent = evento.customer;
                  eventList.appendChild(li);
              });
          } else {
              // Si no hay resultados, mostramos un mensaje
              const li = document.createElement('li');
              li.textContent = 'No sales found';
              eventList.appendChild(li);
          }
      })
      .catch(error => {
        console.log(error)
          //console.error('Error al obtener los eventos:', error);
      });
  });
  </script>
{% endblock %}

apps/sales/templates/sales/sale_list.html
{% extends 'base.html' %}

{% block title %}
  Armfy - Sales
{% endblock %}

{% block style %}
  <style>
    .fab-button {
      position: fixed;
      bottom: 50px; /* Distancia desde el fondo */
      right: 20px; /* Distancia desde la derecha */
      z-index: 1000; /* Asegúrate de que esté por encima de otros elementos */
    }
  </style>
{% endblock %}

{% block barname %}
  Sales
{% endblock %}
{% block content %}
<button class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored fab-button waves-effect waves-light" onclick="location.href='{% url 'sales:sale_create' %}'">
  <i class="material-icons">add</i>
</button>
<div class="mx-card mdl-shadow--4dp mdl-cell mdl-cell--12-col mdl-grid">
{{ obj_table }}
</div>
{% endblock %}

{% block script %}
  <script>
  </script>
{% endblock %}