apps/products/urls.py
# ZeroPaul
from django.urls import path, include
from apps.products.views.product import ProductCountView, ProductListView, ProductDetailView, ProductCreateUpdateView

app_name = 'products'

urlpatterns = [
    # path('example/', ExampleView.as_view(), name='example'),
    path('', ProductCountView.as_view(), name='product_count'),
    path('list/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    
    path('product/create/', ProductCreateUpdateView.as_view(), name='product_create'),
    path('product/<int:pk>/edit/', ProductCreateUpdateView.as_view(), name='product_edit'),
]

armfy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.auths.urls")),
    path('', include("apps.dashboards.urls")),
    path('', include("apps.products.urls")),
    path('', include('apps.sales.urls', namespace='sales')),
]

apps/products/models/length.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _

from .measure import Measure

class Length(models.Model):
    measure_lenght = models.ForeignKey(Measure, on_delete=models.CASCADE, related_name='lenghts')
    number_lenght = models.CharField(max_length=255)

    class Meta:
        # ordering = ['field',]
        verbose_name = _('Length')
        verbose_name_plural = _('Lengths')
    
    def __str__(self):
        return self.number_lenght + str(self.measure_lenght.abbreviation_measure)

apps/products/models/measure.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _

class Measure(models.Model):
    name_measure = models.CharField(max_length=255)
    abbreviation_measure = models.CharField(max_length=255)
    
    class Meta:
        # ordering = ['field',]
        verbose_name = _('Measure')
        verbose_name_plural = _('Measures')

    def __str__(self):
        return self.name_measure

apps/products/models/polygon.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _

class Polygon(models.Model):
    name_polygon = models.CharField(max_length=255, default='I')

    class Meta:
        # ordering = ['field',]
        verbose_name = _('Polygon')
        verbose_name_plural = _('Polygons')

    def __str__(self):
        if self.pk is not None:
            a = ' x '.join(str(side) for side in self.polygon_sides.all())
            if self.name_polygon == 'I':
                self.name_polygon = a
                self.save()
            return a
        else:
            return self.name_polygon
        
    def save(self, *args, **kwargs):
        if self.pk is not None:
            self.name_polygon = ' x '.join(str(side) for side in self.polygon_sides.all())
        super(Polygon, self).save(*args, **kwargs)

apps/products/models/product.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _


class Product(models.Model):

    class Meta:
        # ordering = ['field',]
        verbose_name = _('Product')
        verbose_name_plural = _('Products')

    # def __str__(self):
    #     return self.get_reverse_relation_name()
    
    def __str__(self):
        if not hasattr(self, '_full_name_cache'):
            self._full_name_cache = self.get_reverse_relation_name()
        return self._full_name_cache
    
    def get_reverse_relation_name(self):
        # print("get reversed")
        r = None
        related_names_all = self.get_related_names()
        for related_name in related_names_all:
            if hasattr(self, related_name):
                related_instance = getattr(self, related_name)
                try:
                    if related_instance.exists():
                        r = related_instance.__str__()
                except Exception as e:
                    # print('error', e)
                    r = related_instance.__str__()
                break
            
            else:
                r = f'{self.id} product is not assigned to any type'
        return r
            

    def get_related_names(self):
        product_meta = Product._meta
        related_names = []

        for field in product_meta.get_fields():
            if field.is_relation and field.related_name:
                # if not field.related_name.startswith(('pric', 'pra')):
                related_names.append(field.related_name)
        
        related_names.append('null')

        return related_names

# Proxy Model


class ProductsProfileSteel(Product):
    class Meta:
        proxy = True


class ProductsWelding(Product):
    class Meta:
        proxy = True

apps/products/models/shape.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _

class Shape(models.Model):
    name_shape = models.CharField(max_length=255)
    class Meta:
        # ordering = ['field',]
        verbose_name = _('Shape')
        verbose_name_plural = _('Shapes')

    def __str__(self):
        return self.name_shape

apps/products/models/side.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _

from .measure import Measure
from .polygon import Polygon


class Side(models.Model):
    name_side = models.CharField(max_length=255)
    measure_side = models.ForeignKey(Measure, on_delete=models.CASCADE, related_name='sides')

    class Meta:
        # ordering = ['field',]
        verbose_name = _('Side')
        verbose_name_plural = _('Sides')

    def __str__(self):
        return self.name_side + ' ' + str(self.measure_side.abbreviation_measure)


class GroupSide(models.Model):
    # fields
    side = models.ForeignKey(Side, on_delete=models.CASCADE, related_name='group_sides')
    polygon = models.ForeignKey(Polygon, on_delete=models.CASCADE, related_name='polygon_sides')

    class Meta:
        # ordering = ['name',]
        verbose_name = _('GroupSide')
        verbose_name_plural = _('GroupSides')

    def __str__(self):
        return str(self.side.name_side)

apps/products/models/texture.py
# ZeroPaul
from django.db import models
from django.utils.translation import gettext_lazy as _


class Texture(models.Model):
    name_texture = models.CharField(max_length=255)

    class Meta:
        # ordering = ['field',]
        verbose_name = _('Texture')
        verbose_name_plural = _('Textures')

    def __str__(self):
        return self.name_texture

apps/products/forms/product.py
# forms.py
# from django import forms
from apps.templifys.models import ModelChoiceField
from apps.templifys.models import ModelForm
from apps.templifys import widgets

from apps.products.models.product import Product
from apps.products.models.profilesteel import ProfileSteel, TypeProfileSteel
from apps.products.models.welding import Welding


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

from django.db import models
class DynamicWidget():
    fields_widgets = {
        models.CharField: widgets.TextInput,
        models.IntegerField: widgets.NumberInput,
        models.EmailField: widgets.EmailInput,
        models.DateField: widgets.DateInput(attrs={'type': 'date'}),
        models.BooleanField: widgets.CheckboxInput,
        models.TextField: widgets.Textarea,
        models.FloatField: widgets.NumberInput,
        models.DecimalField: widgets.NumberInput,
        models.FileField: widgets.ClearableFileInput,
        models.ImageField: widgets.ClearableFileInput,
        models.URLField: widgets.URLInput,
        models.PositiveIntegerField: widgets.NumberInput,
        models.PositiveSmallIntegerField: widgets.NumberInput,
        models.SlugField: widgets.TextInput,
        models.TimeField: widgets.TimeInput(attrs={'type': 'time'}),
        models.GenericIPAddressField: widgets.TextInput,
        models.ForeignKey: widgets.Select(),
        models.ManyToManyField: widgets.CheckboxSelectMultiple,
        models.OneToOneField: widgets.Select(),
    }

    def __init__(self, model, fields):
        self.model = model
        self.fields = fields

    def generate_widgets(self):
        widgets = {}
        for field in self.model._meta.get_fields():
            if field.name in self.fields:
                widget = self.fields_widgets.get(type(field))
                widgets[field.name] = widget
                # print(f'Nombre: {field.name}, Tipo: {widget}')
        return widgets


class ProfileSteelForm(ModelForm):
    class Meta():
        model = ProfileSteel
        fields = ['type_profile_steel', 'texture', 'shape',
                  'polygon', 'thickness', 'length', 'steel']
        widgets = DynamicWidget(model=model, fields=fields).generate_widgets()
   


class WeldingForm(ModelForm):
    class Meta:
        model = Welding
        fields = ['brand', 'type_welding', 'thickness', 'package']
        widgets = DynamicWidget(model=model, fields=fields).generate_widgets()


# from django.forms import ModelForm, Textarea
# from apps.templifys.widgets import Select

# class AuthorForm(ModelForm):
#     class Meta:
#         model = Author
#         fields = ('name', 'title', 'birth_date')
#         widgets = {
#             'name': Textarea(attrs={'cols': 80, 'rows': 20}),
#         }

apps/products/views/product.py
import json
from django.http import JsonResponse
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404

from apps.products.models.profilesteel import ProfileSteel, TypeProfileSteel
from apps.products.models.steel import Steel
from apps.products.models.welding import Welding
from apps.products.models.product import Product
from apps.products.forms.product import ProductForm, WeldingForm, ProfileSteelForm


from apps.templifys.builders.base import Scoreboard
# views.py


class ProductCountView(LoginRequiredMixin, TemplateView):
    # template_name = 'products/index.html'
    template_name = 'products/test.html'

    def get_steel_count(self):
        data_count = []
        for s in Steel.objects.all():
            data_count.append(
                {"name":s.__str__(), "value": ProfileSteel.objects.filter(steel=s).count()}
            )
        return json.dumps(data_count)
    
    def get_sales(self):
        from django.utils import timezone
        from datetime import timedelta
        from apps.sales.models.sale import Sale
        hoy = timezone.now().date()
        r = Sale.objects.filter(date_sale__date=hoy).count()
        return r
    
    def get_stock(self):
        from django.db.models import F
        from apps.branches.models.stock import Stock
        count = Stock.objects.filter(total_quantity__lt=F('min_stock')).count()
        return count
    
    def get_cash(self):
        from django.utils import timezone
        from apps.sales.models.sale import Sale
        hoy = timezone.now().date()
        objetos = Sale.objects.filter(date_sale__date=hoy)
        a = 0
        for obj in objetos:
            a += obj.total
        return a
    
    def get_brach(self):
        from apps.branches.models.branch import Branch
        r = Branch.objects.filter(branch_status=True).count()
        return r
    
    
    def get_products_sale(self):
        from django.db.models import Sum
        from apps.sales.models.sale import SaleDetail
        from django.utils import timezone
        hoy = timezone.now().date()
        from django.db.models import Prefetch
        productos_prefetch = Product.objects.all()
        detalles = (SaleDetail.objects
            .filter(sale__date_sale__date=hoy)
            .prefetch_related(Prefetch('product', queryset=productos_prefetch))
            .values('product')
            .annotate(cantidad_total=Sum('quantity')))
        
        data = []
        for detalle in detalles:
            producto = detalle['product']
            data.append({'name': Product.objects.get(id=producto).__str__(), 'value': detalle['cantidad_total']})

        return json.dumps(data)
        

    def get_context_data(self, **kwargs):
        # print(Scoreboard().render())
        context = super().get_context_data(**kwargs)
        data = [
            {"name": "Metal", "value": ProfileSteel.objects.count()},
            {"name": "Welding", "value": Welding.objects.count()},
        ]
        
        context['data'] = json.dumps(data)
        context['steel'] = self.get_steel_count()
        context['sales'] = self.get_products_sale()
        context['menu_active'] = 'dashboard'
        context['obj_stock'] = Scoreboard({'name': 'Stock Alerts', 'value': f'# { self.get_stock() }', 'icon': 'report_problem', 'color': 'red'}).render()
        context['obj_sale'] = Scoreboard({'name': 'Sales', 'value': f'# { self.get_sales() }', 'icon': 'shopping_cart', 'color': 'blue' }).render()
        context['obj_cash'] = Scoreboard({'name': 'Cash', 'value': f'S/ { self.get_cash() }', 'icon': 'attach_money', 'color': '#4b147c' }).render()
        context['obj_branch'] = Scoreboard({'name': 'Branches', 'value': f'# { self.get_brach() }', 'icon': 'business', 'color': '#4f894e' }).render()
        return context


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products_list'
    paginate_by = 7

    def get_queryset(self):
        return Product.objects.all().order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_active'] = 'products'
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        data = {
            'id': self.object.id,
            'datar': self.object.__str__(),
            'name': 'namer',
            'description': 'description',
        }
        return JsonResponse(data)


class DynamicRelationModel():
    model = None
    classes_model_form = []

    related_names = []

    def get_related_names(self):
        obj_meta = self.model._meta

        for field in obj_meta.get_fields():
            if field.is_relation and field.related_name:
                self.related_names.append(field.related_name)
        return self.related_names

    def relation_model(self, pk):
        try:
            query = self.model.objects.get(id=pk)
        except self.model.DoesNotExist:
            return None, None

        for related_name in self.get_related_names():
            related_instance = getattr(query, related_name, None)
            if related_instance is not None:
                model_obj, form_obj = self.model_classes[related_instance.__class__.__name__]
                # return related_name, related_instance.__class__.__name__
                return model_obj, form_obj
        return None, None

    def change_form(self, model_str):
        model_obj, form_obj = self.model_classes[model_str]
        return form_obj

    def get_fields(self):
        # all_fields = []
        # for field in ProfileSteel._meta.get_fields():
        #     all_fields.append(field.name)
        #     # print(f'  Campo: {field.name} - Tipo: {field.get_internal_type()}')
        # print(all_fields)
        pass
        # self.change_form('ProfileSteel')


class ProductCreateUpdateView(View, DynamicRelationModel):
    model = Product
    model_classes = {
        'ProfileSteel': (ProfileSteel, ProfileSteelForm),
        'Welding': (Welding, WeldingForm),
    }
    
    def runner(self):
        all_fields = []
        for field in Welding._meta.get_fields():
            all_fields.append(field.name)
            # print(f'  Campo: {field.name} - Tipo: {field.get_internal_type()}')
        print(all_fields)

    def get(self, request, pk=None, *args, **kwargs):
        # self.runner()
        if pk:
            product = get_object_or_404(Product, pk=pk)
            model_obj, form_obj = self.relation_model(pk=pk)
            obj_get = get_object_or_404(model_obj, product=product)
            obj_form = form_obj(instance=obj_get)

            self.get_fields()
        else:  # Creación
            type_pro = request.GET.get('type_products')
            if type_pro is None:
                type_pro = 'ProfileSteel'
            retry_form = self.change_form(type_pro)
            obj_form = retry_form()
            
        return render(request, 'products/product_form.html', {
            'obj_form': obj_form,
            'is_editing': pk is not None
        })

    def post(self, request, pk=None, *args, **kwargs):
        if pk:  # Editando
            product = get_object_or_404(Product, pk=pk)
            model_obj, form_obj = self.relation_model(pk=pk)
            obj_get = get_object_or_404(model_obj, product=product)
            obj_form = form_obj(request.POST, instance=obj_get)
        else:  # Creando
            # product = Product.objects.create()
            type_pro = request.GET.get('type_products')
            if type_pro is None:
                type_pro = 'ProfileSteel'
            retry_form = self.change_form(type_pro)
            obj_form = retry_form(request.POST)

        if obj_form.is_valid():
            if pk is None:
                product = Product.objects.create()
            obj_sub = obj_form.save(commit=False)
            obj_sub.product = product
            obj_sub.save()
            return redirect(reverse_lazy('products:product_list'))

        return render(request, 'products/product_form.html', {
            'obj_form': obj_form,
            'is_editing': pk is not None
        })

apps/products/templates/products/form_steel.html
{% comment %} <form method="post">
    {% csrf_token %}
    {{ obj_form.as_p }}

    <button type="submit">{% if is_editing %}Actualizar{% else %}Crear{% endif %}</button>
  </form>
  <a href="{% url 'products:product_list' %}">Volver a la lista</a> {% endcomment %}

apps/products/templates/products/g.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Input Required con Material Lite</title>
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <style>
        .error {
            border-bottom: 1px solid red; /* Estilo de error */
        }
    </style>
</head>
<body>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input class="mdl-textfield__input" type="text" id="sample3" required>
        <label class="mdl-textfield__label" for="sample3">UserName</label>
    </div>

    <script>
        const input = document.getElementById('sample3');

        // Asegúrate de que no esté en rojo al cargar
        input.classList.remove('error');

        input.addEventListener('focus', () => {
            input.classList.remove('error'); // Elimina el estilo de error al enfocar
        });

        input.addEventListener('blur', () => {
            if (!input.value) {
                input.classList.add('error'); // Agrega el estilo de error si está vacío
            }
        });
    </script>

</body>
</html>

apps/products/templates/products/index.html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
    .container-nx {
        display: flex;
        justify-content: space-evenly;
        flex-direction: row;
    }
    .card-square.mdl-card {
        width: 360px;
        height: 360px;
      }
</style>

<div class="container-nx">
    <div class="card-square mdl-card mdl-shadow--16dp">
        <div class="mdl-card__title mdl-card--expand">
            <canvas id="myPieChart" width="500" height="500"></canvas>
        </div>
    </div>
    
    <div class="card-square mdl-card mdl-shadow--16dp">
        <div class="mdl-card__supporting-text">
            <canvas id="myLineChart" width="500" height="500"></canvas>
        </div>
    </div>
</div>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var ctx = document.getElementById('myPieChart').getContext('2d');
        var myPieChart = new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels:  {{ category|safe }},//['Producto A', 'Producto B', 'Producto C'], // Etiquetas para los segmentos
                datasets: [{
                    label: 'Cantidad de Productos Registrados',
                    data: {{ count|safe }}, // Datos para cada segmento
                    backgroundColor: [
                        'red',
                        'blue',
                    ],
                    
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'Productos por Categoria'
                    }
                }
            }
        });

        // Gráfico de líneas
        var ctxLine = document.getElementById('myLineChart').getContext('2d');
        var myLineChart = new Chart(ctxLine, {
            type: 'line',
            data: {
                labels: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'],  // Cambia por tus etiquetas
                datasets: [{
                    label: 'Productos vendidos',
                    data: [12, 19, 3, 5, 2],  // Cambia por tus datos
                    fill: true,
                    borderColor: 'rgba(75, 192, 192, 1)',
                    tension: 0.1
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                        text: 'Ventas de Productos a lo largo de los meses'
                    }
                }
            }
        });


    });
    
</script>

apps/products/templates/products/product_list.html
{% extends 'base.html' %}

{% block title %}
  Armfy
{% endblock %}

{% block style %}
  <style>
    .fab-button {
      position: fixed;
      bottom: 50px; /* Distancia desde el fondo */
      right: 20px; /* Distancia desde la derecha */
      z-index: 1000; /* Asegúrate de que esté por encima de otros elementos */
    }
    
  </style>
{% endblock %}
{% block barname %}
  Products All
{% endblock %}
{% block content %}
  <button class="mdl-button mdl-js-button mdl-button--fab mdl-button--colored fab-button waves-effect waves-light" onclick="location.href='{% url 'products:product_create' %}'">
    <i class="material-icons">add</i>
  </button>
  <div class="mx-card mdl-shadow--4dp  mdl-cell mdl-cell--12-col mdl-grid">
    <table class="mdl-data-table mdl-js-data-table">
      <thead>
        <tr>
          <th class="mdl-data-table__cell--non-numeric">Product</th>
          <th>Category</th>
          <th>Stock</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for product in products_list %}
          <tr>
            <td class="mdl-data-table__cell--non-numeric">{{ product }}</td>
            <td>edit / delete</td>
            <td>edit / delete</td>
            <td>
              {% comment %} <form action="{% url 'products:product_edit' product.id %}" method="get"> {% endcomment %}
                <button class="mdl-button mdl-js-button mdl-button--icon" onclick="location.href='{% url 'products:product_edit' product.id %}'"><i class="material-icons">edit</i></button>
              {% comment %} </form> {% endcomment %}
              <button class="mdl-button mdl-js-button mdl-button--icon open-modal" data-product-id="{{ product.id }}" data-micromodal-trigger="modal-{{ product.id }}"><i class="material-icons open-modal" data-product-id="{{ product.id }}" data-micromodal-trigger="modal-{{ product.id }}">details</i></button>
            </td>
          </tr>

          <div class="modal micromodal-slide overlay" id="modal-{{ product.id }}" aria-hidden="true">
            <div class="modal__overlay">
              <div class="modal__container">
                <header class="modal__header">
                  <span>Detail Product</span>
                </header>
                <div class="modal__content" id="modal-content-{{ product.id }}"></div>
                <footer class="modal__footer">
                  <button class="modal__close mdl-button mdl-js-button mx-button-accent waves-effect waves-light" data-micromodal-close>Close</button>
                  <button class="mdl-button mdl-js-button mx-button-primary waves-effect waves-light">Save</button>
                </footer>
              </div>
            </div>
          </div>
        {% endfor %}
      </tbody>
    </table>
    {% if is_paginated %}
      <div class="mx-pagination">
        <span class="mx-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>
        <span class="step-links">
          {% if page_obj.has_previous %}
            <button class="mdl-button mdl-js-button mdl-button--icon" id="firts-link" data-url="?page=1"><i class="material-icons">first_page</i></button>
            <button class="mdl-button mdl-js-button mdl-button--icon" id="left-link" data-url="?page={{ page_obj.previous_page_number }}"><i class="material-icons">keyboard_arrow_left</i></button>
          {% else %}
            <button class="mdl-button mdl-js-button mdl-button--icon" disabled><i class="material-icons">first_page</i></button>
            <button class="mdl-button mdl-js-button mdl-button--icon" disabled><i class="material-icons">keyboard_arrow_left</i></button>
          {% endif %}
          {% if page_obj.has_next %}
            <button class="mdl-button mdl-js-button mdl-button--icon" id="right-link" data-url="?page={{ page_obj.next_page_number }}"><i class="material-icons">keyboard_arrow_right</i></button>
            <button class="mdl-button mdl-js-button mdl-button--icon" id="last-link" data-url="?page={{ page_obj.paginator.num_pages }}"><i class="material-icons">last_page</i></button>
          {% else %}
            <button class="mdl-button mdl-js-button mdl-button--icon" disabled><i class="material-icons">keyboard_arrow_right</i></button>
            <button class="mdl-button mdl-js-button mdl-button--icon" disabled><i class="material-icons">last_page</i></button>
          {% endif %}
        </span>
      </div>
    {% endif %}
  </div>

  <div class="modal micromodal-slide overlay" id="modal-1" aria-hidden="true">
    <div class="modal__container">
      <header class="modal__header">
        <h2 class="modal__title">Título del Modal</h2>
        <button class="modal__close" aria-label="Close modal" data-micromodal-close></button>
      </header>
      <main class="modal__content" id="modal-content">
        <p>Este es el contenido del modal.</p>
      </main>
      <footer class="modal__footer">
        <button class="modal__btn" data-micromodal-close>Cerrar</button>
        <button data-custom-close="modal-1">close</button>
      </footer>
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    redirectUrl('firts-link')
    redirectUrl('left-link')
    redirectUrl('right-link')
    redirectUrl('last-link')
    
    function createItem(icon, data) {
      const item_data = document.createElement('li')
      item_data.classList.add('mdl-list__item')
      const span_data = document.createElement('span')
      span_data.classList.add('mdl-list__item-primary-content')
      const icon_data = document.createElement('icon')
      icon_data.classList.add('material-icons', 'mdl-list__item-icon')
    
      icon_data.textContent = icon
      const text_data = document.createTextNode(data)
    
      item_data.appendChild(span_data)
      span_data.appendChild(icon_data)
      span_data.appendChild(text_data)
      return item_data
    }
    document.addEventListener('click', function (event) {
      if (event.target.matches('.open-modal')) {
        const productId = event.target.dataset.productId
    
        // Realiza una solicitud AJAX para obtener los detalles del producto
        fetch(`/product/${productId}/`)
          .then((response) => response.json())
          .then((data) => {
            // Inserta los datos en el modal
            const modalContent = document.getElementById(`modal-content-${productId}`)
            const list_data = document.createElement('ul')
            list_data.classList.add('mdl-list')
            const item_id = createItem('developer_board', data.id)
            list_data.appendChild(item_id)
            const item_data = createItem('person', data.datar)
            list_data.appendChild(item_data)
    
            const htmlString = list_data.outerHTML
            modalContent.innerHTML = htmlString
          })
          .catch((error) => console.error('Error:', error))
      }
    })
    document.addEventListener('.close__modal', function (event) {
      const modalId = event.detail.modal.id
      console.log(`Modal cerrado: ${modalId}`)
    })
  </script>
{% endblock %}