apps/auths/urls.py
# ZeroPaul
from django.urls import path, include
from apps.auths.views.login import LoginView,LogoutView, ChangePasswordView
# from django.contrib.auth.views import LogoutView

app_name = 'auths'

urlpatterns = [
    # path('example/', ExampleView.as_view(), name='example'),
    path('login/', LoginView.as_view(), name='login'),
    # path('logout/', LogoutView.as_view(), name='logout'),
    path('logout/', LogoutView.as_view(), name='logout'),
     path('change-password/', ChangePasswordView.as_view(), name='change_password'),
]

apps/products/urls.py
# ZeroPaul
from django.urls import path, include
from apps.products.views.product import ProductCountView, ProductListView, ProductDetailView, ProductCreateUpdateView

app_name = 'products'

urlpatterns = [
    # path('example/', ExampleView.as_view(), name='example'),
    path('', ProductCountView.as_view(), name='product_count'),
    path('list/', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    
    path('product/create/', ProductCreateUpdateView.as_view(), name='product_create'),
    path('product/<int:pk>/edit/', ProductCreateUpdateView.as_view(), name='product_edit'),
]

apps/sales/urls.py
# ZeroPaul
from django.urls import path, include
from apps.sales.views.sale import SaleListView, SaleCreateUpdateView, ProductAutocompleteView
from apps.sales.views.pdf import SalePDFView


app_name = 'sales'

urlpatterns = [
    path('sale/', SaleListView.as_view(), name='sale_list'),
    path('sale/create/', SaleCreateUpdateView.as_view(), name='sale_create'),
    path('sale/<int:pk>/edit/', SaleCreateUpdateView.as_view(), name='sale_edit'),
    path('sale-product/', ProductAutocompleteView.as_view(), name='sale_auto_product'),
    path(
        route ='sale-pdf/<int:pk>/',
        view = SalePDFView.as_view(),
        name = 'sale_pdf'
    ),
]

armfy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.auths.urls")),
    path('', include("apps.dashboards.urls")),
    path('', include("apps.products.urls")),
    path('', include('apps.sales.urls', namespace='sales')),
]

apps/auths/models/menu.py
# menu.py
class MenuItem:
    def __init__(self, name, url, children=None):
        self.name = name
        self.url = url
        self.children = children if children else []

    def __str__(self):
        return f"{self.name} ({self.url})"

# Definir el menú
menu = [
    MenuItem("Inicio", "/"),
    MenuItem("Productos", "/productos", [
        MenuItem("Categoría 1", "/productos/categoria-1"),
        MenuItem("Categoría 2", "/productos/categoria-2")
    ]),
    MenuItem("Contacto", "/contacto")
]

for item in menu:     
    print(item.name)  
    if item.children:
        for child in item.children:
            print(child.name)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Armfy{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/material-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/waves.css' %}">
    <link rel="stylesheet" href="{% static 'css/material.css' %}">
    <link rel="stylesheet" href="{% static 'css/select.css' %}">
    <link rel="stylesheet" href="{% static 'css/c3.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/micromodal.css' %}">
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/micromodal/dist/micromodal.css" /> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/mode.css' %}">
    <link rel="stylesheet" href="{% static 'css/inputs.css' %}">
    {% block style %}{% endblock %}
</head>

<body>
    <div class="mx-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
        <header class="mx-header mdl-layout__header">
            <div class="mdl-layout__header-row">
                <!-- <div aria-expanded="true" role="button" class="mdl-layout__drawer-button"><i class="material-icons">home</i></div> -->
                <span class="mdl-layout-title">
                    {% block barname %}Armfy{% endblock %}
                </span>
                <div class="mdl-layout-spacer"></div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable">
                    <label class="mdl-button mdl-js-button mdl-button--icon" for="search">
                        <i class="material-icons">search</i>
                    </label>
                    <div class="mdl-textfield__expandable-holder">
                        <input class="mdl-textfield__input" type="text" id="search">
                        <label class="mdl-textfield__label" for="search">Enter your query...</label>
                    </div>
                </div>
                <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon" id="hdrbtn">
                    <i class="material-icons">more_vert</i>
                </button>
                <ul class="mdl-menu mdl-js-menu mdl-js-ripple-effect mdl-menu--bottom-right" for="hdrbtn">
                    <li class="mdl-menu__item" id="admin-link" data-url="{% url 'admin:index' %}">Django Admin</li>
                    <!-- <li class="mdl-menu__item">Contact</li>
                  <li class="mdl-menu__item">Legal information</li> -->
                </ul>
            </div>
        </header>
        {% include 'menu.html' %}
        <main class="mdl-layout__content mx-main">
            <div class="mdl-grid mx-content">
                {% block content %}{% endblock %}
            </div>
        </main>
    </div>

    <script src="{% static 'js/waves.js' %}"></script>
    <script src="{% static 'js/material.js' %}"></script>
    <script src="{% static 'js/select.js' %}"></script>
    <script src="{% static 'js/d3.v5.min.js' %}"></script>
    <script src="{% static 'js/c3.min.js' %}"></script>
    {% comment %} <script src="{% static 'js/micromodal.min.js' %}"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/micromodal/dist/micromodal.min.js"></script>
    <script src="{% static 'js/mode.js' %}"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    {% block script %}{% endblock %}
    <script>
        redirectUrl('admin-link');
        redirectUrl('logout');
        redirectUrl('change_password');
        MicroModal.init();
    </script>
</body>

</html>

templates/menu.html
{% load static %}
<div class="demo-drawer mdl-layout__drawer mdl-layout--no-desktop-drawer-button mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
    <header class="demo-drawer-header">
        <img src="{% static 'img/user.png' %}" class="demo-avatar">
        <div class="demo-avatar-dropdown">
            <span>{{ request.user.email }}</span>
            <div class="mdl-layout-spacer"></div>
            <button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
                <i class="material-icons" role="presentation">arrow_drop_down</i>
                <span class="visuallyhidden">Accounts</span>
            </button>
            <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect mx-menu" for="accbtn">
                <li class="mdl-menu__item"><i class="material-icons mx-item-icon">person</i>Profile User</li>
                <li class="mdl-menu__item" data-url="{% url 'auths:change_password' %}" id="change_password"><i class="material-icons mx-item-icon">vpn_key</i>Change Password</li>
                <li class="mdl-menu__item" data-url="{% url 'auths:logout' %}" id="logout"><i class="material-icons mx-item-icon">exit_to_app</i>Logout</li>
            </ul>
        </div>
    </header>
    <nav class="mx-navigation mdl-navigation mx-nav">
        <a class="mdl-navigation__link waves-effect waves-light {% if menu_active == 'dashboard' %}mx-active-menu{% endif %}" href="{% url 'products:product_count'%}#"><i class="material-icons" role="presentation">dashboard</i>Dashboard</a>
        <a class="mdl-navigation__link waves-effect waves-light {% if menu_active == 'products' %}mx-active-menu{% endif %}" href="{% url 'products:product_list'%}"><i class="material-icons" role="presentation">menu</i>Products</a>
        <a class="mdl-navigation__link waves-effect waves-light {% if menu_active == 'sales' %}mx-active-menu{% endif %}" href="{% url 'sales:sale_list'%}"><i class="material-icons" role="presentation">shopping_cart</i>Sales</a>
        <a class="mdl-navigation__link waves-effect waves-light {% if menu_active == '2' %}mx-active-menu{% endif %}" href="#"><i class="material-icons" role="presentation">report</i>Spam</a>
        <a class="mdl-navigation__link waves-effect waves-light {% if menu_active == '3' %}mx-active-menu{% endif %}" href="#"><i class="material-icons" role="presentation">forum</i>Forums</a>
        <a class="mdl-navigation__link waves-effect waves-light {% if menu_active == '4' %}mx-active-menu{% endif %}" href="#"><i class="material-icons" role="presentation">flag</i>Updates</a>
        <a class="mdl-navigation__link waves-effect waves-light" href="#"><i class="material-icons" role="presentation">local_offer</i>Promos</a>
        <a class="mdl-navigation__link waves-effect waves-light" href="#"><i class="material-icons" role="presentation">shopping_cart</i>Purchases</a>
        <a class="mdl-navigation__link waves-effect waves-light" href="#"><i class="material-icons" role="presentation">people</i>Social</a>
        <a class="mdl-navigation__link waves-effect waves-light" href="#"><i class="material-icons" role="presentation">people</i>Social</a>
        <a class="mdl-navigation__link waves-effect waves-light" href="#"><i class="material-icons" role="presentation">people</i>Social</a>
        <a class="mdl-navigation__link waves-effect waves-light" href="#"><i class="material-icons" role="presentation">people</i>Social</a>
        <div class="mdl-layout-spacer"></div>
    </nav>
</div>